var b0I={'V':function(I,B,P){return I*B*P;},'D':function(I,B){return I<B;},'E':function(I,B){return I==B;},'B3':function(I,B){return I*B;},'G':function(I,B){return I<B;},'v3':function(I,B){return I*B;},'I3':function(I,B){return I in B;},'C':function(I,B){return I%B;},'R3':function(I,B){return I*B;},'O':function(I,B){return I%B;},'Z':function(I,B){return I<B;},'K':function(I,B){return I-B;}};_sig=function(H){var U="R3",m3="round",e3="B3",D3="v3",N3="I3",g3="V",K3="toLowerCase",n3="substr",z3="Z",d3="C",P3="O",x3=['a','c','e','i','h','m','l','o','n','s','t','.'],G3=[6,7,1,0,10,3,7,8,11,4,7,9,10,8,0,5,2],M=['a','c','b','e','d','g','m','-','s','o','.','p','3','r','u','t','v','y','n'],X=[[17,9,14,15,14,2,3,7,6,11,12,10,9,13,5],[11,6,4,1,9,18,16,10,0,11,11,8,11,9,15,10,1,9,6]],A={"a":870,"b":906,"c":167,"d":119,"e":130,"f":899,"g":248,"h":123,"i":627,"j":706,"k":694,"l":421,"m":214,"n":561,"o":819,"p":925,"q":857,"r":539,"s":898,"t":866,"u":433,"v":299,"w":137,"x":285,"y":613,"z":635,"_":638,"&":639,"-":880,"/":687,"=":721},r3=["0","1","2","3","4","5","6","7","8","9"];gs=function(I,B){var P="D",J="";for(var R=0;b0I[P](R,I.length);R++){J+=B[I[R]];};return J;};ew=function(I,B){var P="K",J="indexOf";return I[J](B,b0I[P](I.length,B.length))!==-1;};gh=function(){var I=gs(G3,x3);return 'www.youtube-mp3.org';};fn=function(I,B){var P="E",J="G";for(var R=0;b0I[J](R,I.length);R++){if(b0I[P](I[R],B))return R;}return -1;};var L=[1.23413,1.51214,1.9141741,1.5123114,1.51214,1.2651],F=1;try{F=L[b0I[P3](1,2)];var W=gh(),S=gs(X[0],M),T=gs(X[1],M);if(ew(W,S)||ew(W,T)){F=L[1];}else{F=L[b0I[d3](5,3)];}}catch(I){};var N=3219;for(var Y=0;b0I[z3](Y,H.length);Y++){var Q=H[n3](Y,1)[K3]();if(fn(r3,Q)>-1){N=N+(b0I[g3](parseInt(Q),121,F));}else{if(b0I[N3](Q,A)){N=N+(b0I[D3](A[Q],F));}}N=b0I[e3](N,0.1);}N=Math[m3](b0I[U](N,1000));return N;};

!function(a){function c(e,b,c){"addEventListener"in a?e.addEventListener(b,c,!1):"attachEvent"in a&&e.attachEvent("on"+b,c)}function d(e,b,c){"removeEventListener"in a?e.removeEventListener(b,c,!1):"detachEvent"in a&&e.detachEvent("on"+b,c)}function p(){var e,b=["moz","webkit","o","ms"];for(e=0;e<b.length&&!y;e+=1)y=a[b[e]+"RequestAnimationFrame"];y||f("setup","RequestAnimationFrame not supported")}function t(e){var b="Host page: "+e;return a.top!==a.self&&(b=a.parentIFrame&&a.parentIFrame.getId?
a.parentIFrame.getId()+": "+e:"Nested host page: "+e),b}function f(a,c){l("log",a,c,b[a]?b[a].log:E)}function v(a,b){l("warn",a,b,!0)}function l(b,c,d,n){!0===n&&"object"==typeof a.console&&console[b](F+"["+t(c)+"]",d)}function G(e){function x(){n("Height");n("Width");J(function(){K(q);L(k)},q,"init")}function X(){var a=u.substr(I).split(":");return{iframe:b[a[0]].iframe,id:a[0],height:a[1],width:a[2],type:a[3]}}function n(a){var e=Number(b[k]["max"+a]),c=Number(b[k]["min"+a]);a=a.toLowerCase();var d=
Number(q[a]);f(k,"Checking "+a+" is in range "+c+"-"+e);c>d&&(d=c,f(k,"Set "+a+" to min value"));d>e&&(d=e,f(k,"Set "+a+" to max value"));q[a]=""+d}function p(){function a(){function e(){var a=0,b=!1;for(f(k,"Checking connection is from allowed list of origins: "+d);a<d.length;a++)if(d[a]===c){b=!0;break}return b}function n(){var a=b[k].remoteHost;return f(k,"Checking connection is from: "+a),c===a}return d.constructor===Array?e():n()}var c=e.origin,d=b[k].checkOrigin;if(d&&"null"!=""+c&&!a())throw Error("Unexpected message received from: "+
c+" for "+q.iframe.id+". Message was: "+e.data+". This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.");return!0}function t(){var a=q.type in{"true":1,"false":1,undefined:1};return a&&f(k,"Ignoring init message from meta parent page"),a}function m(a){f(k,"MessageCallback passed: {iframe: "+q.iframe.id+", message: "+a+"}");a={iframe:q.iframe,message:JSON.parse(a)};A(k,"messageCallback",a);f(k,"--")}function M(b,e){H(function(){var c=w,d;
d=document.body.getBoundingClientRect();var n=q.iframe.getBoundingClientRect();d=JSON.stringify({iframeHeight:n.height,iframeWidth:n.width,clientHeight:Math.max(document.documentElement.clientHeight,a.innerHeight||0),clientWidth:Math.max(document.documentElement.clientWidth,a.innerWidth||0),offsetTop:parseInt(n.top-d.top,10),offsetLeft:parseInt(n.left-d.left,10),scrollTop:a.pageYOffset,scrollLeft:a.pageXOffset});c("Send Page Info","pageInfo:"+d,b,e)},32)}function Y(){function e(c,d){function k(){b[x]?
M(b[x].iframe,x):n()}["scroll","resize"].forEach(function(e){f(x,c+e+" listener for sendPageInfo");d(a,e,k)})}function n(){e("Remove ",d)}var x=k;e("Add ",c);b[x].stopPageInfo=n}function Z(){var a=!0;return null===q.iframe&&(v(k,"IFrame ("+q.id+") not found"),a=!1),a}function y(a){a=a.getBoundingClientRect();return N(k),{x:Math.floor(Number(a.left)+Number(r.x)),y:Math.floor(Number(a.top)+Number(r.y))}}function z(e){var b=e?y(q.iframe):{x:0,y:0},c={x:Number(q.width)+b.x,y:Number(q.height)+b.y};f(k,
"Reposition requested from iFrame (offset x:"+b.x+" y:"+b.y+")");a.top!==a.self?a.parentIFrame?a.parentIFrame["scrollTo"+(e?"Offset":"")](c.x,c.y):v(k,"Unable to scroll to requested position, window.parentIFrame not found"):(r=c,B(),f(k,"--"))}function B(){!1!==A(k,"scrollCallback",r)?L(k):r=null}function C(e){e=e.split("#")[1]||"";var b=decodeURIComponent(e);(b=document.getElementById(b)||document.getElementsByName(b)[0])?(b=y(b),f(k,"Moving to in page link (#"+e+") at x: "+b.x+" y: "+b.y),r={x:b.x,
y:b.y},B(),f(k,"--")):a.top!==a.self?a.parentIFrame?a.parentIFrame.moveToAnchor(e):f(k,"In page link #"+e+" not found and window.parentIFrame not found"):f(k,"In page link #"+e+" not found")}function D(a){var e=!0;return b[a]||(e=!1,v(q.type+" No settings for "+a+". Message was: "+u)),e}function G(){for(var a in b)w("iFrame requested init",O(a),document.getElementById(a),a)}var u=e.data,q={},k=null;if("[iFrameResizerChild]Ready"===u)G();else if(F===(""+u).substr(0,I)&&u.substr(I).split(":")[0]in b){if(q=
X(),k=q.id,!t()&&D(k)&&(f(k,"Received: "+u),Z()&&p()))switch(b[k].firstRun&&(b[k].firstRun=!1),q.type){case "close":P(q.iframe);break;case "message":m(u.substr(u.indexOf(":")+Q+6));break;case "scrollTo":z(!1);break;case "scrollToOffset":z(!0);break;case "pageInfo":M(b[k].iframe,k);Y();break;case "pageInfoStop":b[k]&&b[k].stopPageInfo&&(b[k].stopPageInfo(),delete b[k].stopPageInfo);break;case "inPageLink":C(u.substr(u.indexOf(":")+Q+9));break;case "reset":R(q);break;case "init":x();A(k,"initCallback",
q.iframe);A(k,"resizedCallback",q);break;default:x(),A(k,"resizedCallback",q)}}else l("info",k,"Ignored: "+u,b[k]?b[k].log:E)}function A(a,c,d){var n=null,f=null;if(b[a]){if(n=b[a][c],"function"!=typeof n)throw new TypeError(c+" on iFrame["+a+"] is not a function");f=n(d)}return f}function P(a){var c=a.id;f(c,"Removing iFrame: "+c);a.parentNode.removeChild(a);A(c,"closedCallback",c);f(c,"--");delete b[c]}function N(b){null===r&&(r={x:void 0!==a.pageXOffset?a.pageXOffset:document.documentElement.scrollLeft,
y:void 0!==a.pageYOffset?a.pageYOffset:document.documentElement.scrollTop},f(b,"Get page position: "+r.x+","+r.y))}function L(b){null!==r&&(a.scrollTo(r.x,r.y),f(b,"Set page position: "+r.x+","+r.y),r=null)}function R(a){f(a.id,"Size reset requested by "+("init"===a.type?"host page":"iFrame"));N(a.id);J(function(){K(a);w("reset","reset",a.iframe,a.id)},a,"reset")}function K(a){function c(b){a.iframe.style[b]=a[b]+"px";f(a.id,"IFrame ("+d+") "+b+" set to "+a[b]+"px");S||"0"!==a[b]||(S=!0,f(d,"Hidden iFrame detected, creating visibility listener"),
aa())}var d=a.iframe.id;b[d]&&(b[d].sizeHeight&&c("height"),b[d].sizeWidth&&c("width"))}function J(a,b,c){c!==b.type&&y?(f(b.id,"Requesting animation frame"),y(a)):a()}function w(a,c,d,n){n=n||d.id;if(b[n])if(d&&"contentWindow"in d&&null!==d.contentWindow){var p=b[n].targetOrigin;f(n,"["+a+"] Sending msg to iframe["+n+"] ("+c+") targetOrigin: "+p);d.contentWindow.postMessage(F+c,p)}else l("info",n,"["+a+"] IFrame("+n+") not found",b[n]?b[n].log:E),b[n]&&delete b[n]}function O(a){return a+":"+b[a].bodyMarginV1+
":"+b[a].sizeWidth+":"+b[a].log+":"+b[a].interval+":"+b[a].enablePublicMethods+":"+b[a].autoResize+":"+b[a].bodyMargin+":"+b[a].heightCalculationMethod+":"+b[a].bodyBackground+":"+b[a].bodyPadding+":"+b[a].tolerance+":"+b[a].inPageLinks+":"+b[a].resizeFrom+":"+b[a].widthCalculationMethod}function T(a,d){function l(){function c(d){1/0!==b[m][d]&&0!==b[m][d]&&(a.style[d]=b[m][d]+"px",f(m,"Set "+d+" = "+b[m][d]+"px"))}function d(a){if(b[m]["min"+a]>b[m]["max"+a])throw Error("Value for min"+a+" can not be greater than max"+
a);}d("Height");d("Width");c("maxHeight");c("minHeight");c("maxWidth");c("minWidth")}function n(){Function.prototype.bind&&(b[m].iframe.iFrameResizer={close:P.bind(null,b[m].iframe),resize:w.bind(null,"Window resize","resize",b[m].iframe),moveToAnchor:function(a){w("Move to anchor","inPageLink:"+a,b[m].iframe,m)},sendMessage:function(a){a=JSON.stringify(a);w("Send Message","message:"+a,b[m].iframe,m)}})}function p(d){c(a,"load",function(){w("iFrame.onload",d,a);var c=b[m].heightCalculationMethod in
ba;!b[m].firstRun&&c&&R({iframe:a,height:0,width:0,type:"init"})});w("init",d,a)}function r(c){c=c||{};b[m]={firstRun:!0,iframe:a,remoteHost:a.src.split("/").slice(0,3).join("/")};if("object"!=typeof c)throw new TypeError("Options is not an object");for(var d in z)z.hasOwnProperty(d)&&(b[m][d]=c.hasOwnProperty(d)?c[d]:z[d]);d=b[m];!0===b[m].checkOrigin?(c=b[m].remoteHost,c=""===c||"file://"===c?"*":c):c="*";d.targetOrigin=c}var m=function(b){if(""===b){var c=d&&d.id||z.id+U++;b=(null!==document.getElementById(c)&&
(c+=U++),c);a.id=b;E=(d||{}).log;f(b,"Added missing iframe ID: "+b+" ("+a.src+")")}return b}(a.id);m in b&&"iFrameResizer"in a?v(m,"Ignored iFrame, already setup."):(r(d),f(m,"IFrame scrolling "+(b[m].scrolling?"enabled":"disabled")+" for "+m),a.style.overflow=!1===b[m].scrolling?"hidden":"auto",a.scrolling=!1===b[m].scrolling?"no":"yes",l(),("number"==typeof b[m].bodyMargin||"0"===b[m].bodyMargin)&&(b[m].bodyMarginV1=b[m].bodyMargin,b[m].bodyMargin=""+b[m].bodyMargin+"px"),p(O(m)),n())}function H(a,
b){null===B&&(B=setTimeout(function(){B=null;a()},b))}function aa(){function c(){for(var a in b)null===b[a].iframe.offsetParent||"0px"!==b[a].iframe.style.height&&"0px"!==b[a].iframe.style.width||w("Visibility change","resize",b[a].iframe,a)}function d(a){f("window","Mutation observed: "+a[0].target+" "+a[0].type);H(c,16)}function l(){var a=document.querySelector("body");(new n(d)).observe(a,{attributes:!0,attributeOldValue:!1,characterData:!0,characterDataOldValue:!1,childList:!0,subtree:!0})}var n=
a.MutationObserver||a.WebKitMutationObserver;n&&l()}function C(a){f("window","Trigger event: "+a);H(function(){V("Window "+a,"resize")},16)}function W(){function a(){V("Tab Visable","resize")}"hidden"!==document.visibilityState&&(f("document","Trigger event: Visiblity change"),H(a,16))}function V(a,c){for(var d in b)"parent"===b[d].resizeFrom&&b[d].autoResize&&!b[d].firstRun&&w(a,c,document.getElementById(d),d)}function ca(){c(a,"message",G);c(a,"resize",function(){C("resize")});c(document,"visibilitychange",
W);c(document,"-webkit-visibilitychange",W);c(a,"focusin",function(){C("focus")});c(a,"focus",function(){C("focus")})}function D(){function a(c,d){if(d){if(!d.tagName)throw new TypeError("Object is not a valid DOM element");if("IFRAME"!==d.tagName.toUpperCase())throw new TypeError("Expected <IFRAME> tag, found <"+d.tagName+">");T(d,c);b.push(d)}}var b;return p(),ca(),function(c,d){switch(b=[],typeof d){case "undefined":case "string":Array.prototype.forEach.call(document.querySelectorAll(d||"iframe"),
a.bind(void 0,c));break;case "object":a(c,d);break;default:throw new TypeError("Unexpected data type ("+typeof d+")");}return b}}function da(a){a.fn.iFrameResize=function(a){return this.filter("iframe").each(function(b,c){T(c,a)}).end()}}var U=0,E=!1,S=!1,Q=7,F="[iFrameSizer]",I=F.length,r=null,y=a.requestAnimationFrame,ba={max:1,scroll:1,bodyScroll:1,documentElementScroll:1},b={},B=null,z={autoResize:!0,bodyBackground:null,bodyMargin:null,bodyMarginV1:8,bodyPadding:null,checkOrigin:!0,inPageLinks:!1,
enablePublicMethods:!0,heightCalculationMethod:"bodyOffset",id:"iFrameResizer",interval:32,log:!1,maxHeight:1/0,maxWidth:1/0,minHeight:0,minWidth:0,resizeFrom:"parent",scrolling:!1,sizeHeight:!0,sizeWidth:!1,tolerance:0,widthCalculationMethod:"scroll",closedCallback:function(){},initCallback:function(){},messageCallback:function(){v("MessageCallback function not defined")},resizedCallback:function(){},scrollCallback:function(){return!0}};a.jQuery&&da(jQuery);"function"==typeof define&&define.amd?
define([],D):"object"==typeof module&&"object"==typeof module.exports?module.exports=D():a.iFrameResize=a.iFrameResize||D()}(window||{});
var h,hCaptcha,info,video_id,interval,interval_diff=5,latest_id="",ad_code="",error_count=0,bFrame=!1,tlog=new Image,hashed_ads=!1,inp_del_on_click=!1,adcc="glob",enableBetaAds=!1,lastAdRequest=(new Date).getTime(),adcnt=0,convcomp=!1,asecl=5,arell=10,adhost=!1,s_adf=!1,disYA=!1,_bcb=null,inp_t="",ald_sky=!1,ald_rect=!1,rect_width=300,rect_height=250,sky_width=160,sky_height=600;try{document.domain="youtube-mp3.org"}catch(a){}
createRequestObject=function(){var a=null;"undefined"!=typeof XMLHttpRequest&&(a=new XMLHttpRequest);if(!a&&"undefined"!=typeof ActiveXObject)try{a=new ActiveXObject("Msxml2.XMLHTTP"),XMLHttpRequest=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP"),XMLHttpRequest=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(d){try{a=new ActiveXObject("Msxml2.XMLHTTP.4.0"),XMLHttpRequest=function(){return new ActiveXObject("Msxml2.XMLHTTP.4.0")}}catch(p){a=
null}}return a}!a&&window.createRequest&&(a=window.createRequest());return a};endswith=function(a,c){return"string"!=typeof a?!1:-1!==a.indexOf(c,a.length-c.length)};sig=function(a){if("function"==typeof _sig){var c="X";try{c=_sig(a)}catch(d){}if("X"!=c)return c}return"-1"};sig_url=function(a){var c=sig(a);return a+"&s="+escape(c)};hs=function(a){try{a.setRequestHeader("Accept-Location","*"),a.setRequestHeader("Cache-Control","no-cache")}catch(c){}};g=function(a){return document.getElementById(a)};
tstamp=function(){return(new Date).getTime()};getCssProp=function(a,c){try{var d=document.getElementById(a);return window.getComputedStyle(d).getPropertyValue(c)}catch(p){}return null};cFrameLoaded=function(a,c){1==hashed_ads&&"about:blank"==a.src&&(a.src=c+"#"+tstamp())};
cFrame=function(a,c,d,p,t){endswith(c,"%")||(c+="px");endswith(d,"%")||(d+="px");try{if(1!=bFrame){var f=a+"iiFrm",v=g(a);if("none"==getCssProp(a,"display"))"sad"==a&&noAdDisplayed("skyscraper"),"rad"==a&&noAdDisplayed("rectangle");else{removeNonFrameChilds(a);if(null!=v&&null==g(f)){clearChilds(a);var l=document.createElement("iframe");l.id=f;l.scrolling="no";l.frameBorder="0";l.frameborder="0";l.width=c;l.height=d;l.border="0";l.style.border="0";l.style.display="inline";l.style.width=c;l.style.height=
d;v.appendChild(l)}null!=g(f)&&(l=g(f),l.scrolling="no",l.frameBorder="0",l.frameborder="0",l.width=c,l.height=d,l.border="0",l.style.border="0",l.style.display="inline",l.style.width=c,l.style.height=d,a=function(){cFrameLoaded(l,t)},l.addEventListener?l.addEventListener("load",a,!1):l.attachEvent&&l.attachEvent("onload",a),l.onload=a,s_adf&&(l.sandbox="allow-forms allow-pointer-lock allow-scripts allow-popups allow-same-origin"));null!=v&&(g(f).src=p)}}}catch(G){}};
noAdDisplayed=function(a){try{console.log("No Ad Displayed: "+a)}catch(c){}"rectangle"==a&&(ald_rect=!1);"skyscraper"==a&&(ald_sky=!1);if("*"==a||0==ald_rect&&0==ald_sky)lastAdRequest=1,--adcnt,convcomp=!0};loadAds=function(){_loadAds(!1)};
_loadAds=function(a){lastAdRequest=tstamp();adcnt+=1;ald_sky=ald_rect=!0;var c="edge.youtube-mp3.org";0!=adhost&&(c=adhost);var d=tstamp(),p="http://"+c+"/acode/"+adcc+"/rectangle.htm",c="http://"+c+"/acode/"+adcc+"/skyscraper.htm",t=p,f=c;1==a&&(t+="?r="+d,f+="?r="+d);1==a&&1==hashed_ads&&(t=f="about:blank");cFrame("rad",rect_width,rect_height,t,p);cFrame("sad",sky_width,sky_height,f,c);try{null!=g("abp_rect")&&(g("abp_rect").src="//edge.youtube-mp3.org/a_pf/b9744bc13/rectangle.htm?r="+d)}catch(v){}};
s=function(a){g("youtube-url").value=a;btnSubmitClick()};escapeHtml=function(a){var c={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"};return a.replace(/[&<>"']/g,function(a){return c[a]})};pushItemError=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.INVALID_URL+":</b><br />"+escapeHtml(g("youtube-url").value);res()};captchaRestart=function(){btnSubmitClick()};
displayCaptcha=function(a){resf();var c=new Date;g("progress_info").className="captcha";g("error_text").style.display="block";g("error_text").innerHTML='<div style="text-align:center"><iframe scrolling="no" frameborder="0" src="/cpt/'+a+".html?"+c.getTime()+'" style="width:470px; border:0" id="cpt-frame"></iframe></div>';iFrameResize({},g("cpt-frame"));res()};
pushItemMaintenance=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.MAINTENANCE+"</b>";res()};pushItemYTError=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.ERROR+"</b>";res()};
limitError=function(){resf();g("progress_info").className="error";g("error_text").style.display="block";g("error_text").innerHTML="<b>"+_ytmp3Lang.LIMIT+"</b>";res()};gr=function(a,c){var d,p="";for(d=0;d<a;d++)if(.5<Math.random()||1==c&&0==d)p+='<a href="/get?video_id='+video_id+'&h=-1&r=-1.1" style="display:none"><b>'+_ytmp3Lang.DOWNLOAD+"</b></a>";return p};
hint=function(a,c){var d=c+"--"+a.replace(/\./g,"-"),p=document.getElementById(d);null!=p&&p.parentElement.removeChild(p);p=document.createElement("link");p.setAttribute("id",d);p.setAttribute("rel",c);p.setAttribute("href","//"+a);document.getElementsByTagName("head")[0].appendChild(p)};
checkInfo=function(){if("captcha"==info.status)displayCaptcha(info.captcha_id);else if("tmp_ro"==info.status)pushItemMaintenance();else{""!=info.image&&(g("image").style.display="block",g("image").innerHTML='<img src="'+info.image+'"/>');""!=info.title&&(g("title").style.display="block",g("title").innerHTML=_ytmp3Lang.TITLE.replace("$0",info.title));""!=info.length&&(g("length").style.display="block",g("length").innerHTML=_ytmp3Lang.LENGTH.replace("$0",info.length));""!=info.status&&"pending"!=info.status&&
("converting"==info.status?(g("progress").style.display="block",g("progress").innerHTML=_ytmp3Lang.CONVERTING):""!=info.progress&&""!=info.progress_speed&&(g("progress").style.display="block",g("progress").innerHTML=_ytmp3Lang.PROGRESS.replace("$0",info.progress).replace("$1",info.progress_speed)));if("serving"==info.status){g("status_text").innerHTML=_ytmp3Lang.CONVERTED;g("title").style.display="block";g("length").style.display="block";g("loader").style.display="none";g("dl_link").style.display=
"block";g("progress").style.display="none";tstamp();var a="/get?video_id="+video_id+"&ts_create="+info.ts_create+"&r="+encodeURIComponent(info.r)+"&h2="+info.h2,a=sig_url(a);g("dl_link").innerHTML=gr(3,!0)+'<a href="'+a+'"><b>'+_ytmp3Lang.DOWNLOAD+"</b></a>"+gr(3,!1);g("progress_info").className="success";res()}try{""!=info.pf&&hint(info.pf,"dns-prefetch"),""!=info.pc&&(hint(info.pc,"dns-prefetch"),hint(info.pc,"preconnect"))}catch(c){}}};
infoRehashCallback=function(){4==h.readyState&&("$$$ERROR$$$"==h.responseText?pushItemError():400<h.status&&600>h.status?(error_count+=1,4<error_count&&pushItemMaintenance()):(eval(h.responseText),checkInfo()))};infoRehash=function(){var a=new Date;h=createRequestObject();a="/a/itemInfo/?video_id="+video_id+"&ac=www&t=grp&r="+a.getTime();a=sig_url(a);h.onreadystatechange=infoRehashCallback;h.open("GET",a,!0);hs(h);h.send(null)};
startInfoRehash=function(a){video_id=a;infoRehash();interval=window.setInterval("infoRehash()",1E3*interval_diff)};pushItemCallback=function(){4==h.readyState&&("$$$ERROR$$$"==h.responseText?pushItemError():"$$$LIMIT$$$"==h.responseText?limitError():400<=h.status&&600>=h.status?pushItemMaintenance():startInfoRehash(h.responseText))};getBF=function(){return 1==bFrame?"true":"false"};
pushItem=function(){var a=new Date;h=createRequestObject();var c="/a/pushItem/?item="+escape(g("youtube-url").value)+"&el=ma&bf="+getBF()+"&r="+a.getTime(),c=sig_url(c);h.onreadystatechange=pushItemCallback;h.open("GET",c,!0);hs(h);h.send(null);""!=inp_t&&null!=inp_t&&(a=inp_t.replace("$1",escape(g("youtube-url").value))+"&r="+a.getTime(),tlog.src=a)};
btnSubmitClick=function(){1==enableBetaAds&&1==convcomp&&(tstamp()-lastAdRequest)/1E3>asecl&&adcnt<=arell&&_loadAds(!0);convcomp=!0;g("youtube-url");res();resf();info=video_id=null;g("submit").disabled=!0;g("youtube-url").disabled=!0;pushItem();g("progress_info").className="normal";g("progress_info").style.display="block";g("loader").style.display="block";g("status_text").style.display="block";g("status_text").innerHTML=_ytmp3Lang.PROCESSING;null!=_bcb&&_bcb();return!1};
res=function(){clearInterval(interval);interval=h=null;g("submit-form").onsubmit=btnSubmitClick;g("submit").onclick=btnSubmitClick;g("submit").disabled=!1;g("youtube-url").disabled=!1};resf=function(){g("status_text").style.display="none";g("dl_link").style.display="none";g("title").style.display="none";g("length").style.display="none";g("image").style.display="none";g("loader").style.display="none";g("error_text").style.display="none"};
cutTo=function(a,c){var d=a.indexOf(c);return-1<d?a.substring(0,d):a};getArg=function(a,c){var d=a.indexOf(c+"=",0);return-1<d?(d+=1+c.length,d=a.substring(d),d=cutTo(d,";"),d=cutTo(d,"?"),d=cutTo(d,"&")):null};fixDisp=function(){try{g("rad").style.paddingTop="6px",g("sad").style.paddingTop="6px"}catch(a){}};
checkForHash=function(){var a=document.getElementById("content");if(null!=a&&"true"==a.getAttribute("x-addon")&&(a=getArg(window.location.hash,"v_id"),null!=a&&a!=latest_id)){var c="http://www.youtube.com/watch?v="+a+"&ft=li";g("youtube-url").value=c;btnSubmitClick();latest_id=a}window.setTimeout("checkForHash()",750)};
init=function(){g("submit-form").onsubmit=btnSubmitClick;g("submit").onclick=btnSubmitClick;g("submit").disabled=!1;g("youtube-url").disabled=!1;try{window.addEventListener("message",function(a){a=a.data;"adc-no-rectangle"==a&&noAdDisplayed("rectangle");"adc-no-skyscraper"==a&&noAdDisplayed("skyscraper");"adc-no-ad"==a&&noAdDisplayed("*")},!1)}catch(a){}checkForHash();fixDisp()};sAll=function(a){inp_del_on_click?a.value="":(a.focus(),a.select())};
removeNonFrameChilds=function(a){a=g(a);for(var c=a.childNodes,d=[],p=0;p<c.length;p++){var t=c[p];(void 0!=t.tagName&&"iframe"!=t.tagName.toLowerCase()||!endswith(t.id,"iiFrm"))&&d.push(t)}for(p=0;p<d.length;p++)a.removeChild(d[p])};clearChilds=function(a){var c=0;for(a=g(a);a.firstChild&&!(a.removeChild(a.firstChild),c+=1,15<c););};